# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computingcomms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionID',
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='quiztest', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
