# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computingcomms', '0002_auto_20180315_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='image',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='forum_images'),
        ),
    ]
