# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computingcomms', '0002_auto_20180308_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(max_length=256),
        ),
    ]
