# Generated by Django 2.0.1 on 2018-03-21 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computingcomms', '0003_auto_20180315_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment', to='computingcomms.ForumPost'),
        ),
    ]
