# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('computingcomms', '0004_auto_20180321_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
