# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computingcomms', '0004_forumpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
