# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computingcomms', '0006_auto_20180320_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='slug',
            field=models.SlugField(),
        ),
    ]
